### ISSUE TITLE
Russian speed.exe is not supported

### ISSUE THREAD

**Issue by adem4ik** [AeroWidescreen/NFSUHDReflections#2]
I have Russian version of NFSU by Soft Club. There is the following message at the start of the game:
![image](https://user-images.githubusercontent.com/4707112/68992613-2b670380-0887-11ea-89f9-f8957d00034e.png)

On the side note NFSUnderground.WidescreenFix works perfectly with my version.

**Comment by AeroWidescreen** [comment]
Only v1.4 (Drunk!) exe is supported. It's works no differently than Extra Options.

> On the side note NFSUnderground.WidescreenFix works perfectly with my version.

Because the widescreen fix checks for bytes to find the memory addresses. The downside is that if any of these bytes are wrong, because of mods or patches, then the game wont work.

**Comment by AeroWidescreen** [comment]
Only v1.4 (Drunk!) exe is supported. It works no differently than Extra Options.

> On the side note NFSUnderground.WidescreenFix works perfectly with my version.

Because the widescreen fix checks for bytes to find the memory addresses. The downside is that if any of these bytes are wrong, because of mods or patches, then the game wont work.
