### ISSUE TITLE
Support for non-US speed.exe v1.4?

### ISSUE THREAD

**Issue by sinisterseed** [AeroWidescreen/NFSUHDReflections#3]
Well, more-or-less what the title says. This is also more of a question rather than a bug report.

Are there any plans (or chances) non-US speed.exe v1.4 will be supported in the future? I have the European version of the game (as part of the Collector's Series bundle) and the mod does not seem to be working correctly (it does load, however, as the mirror settings shows in the menu, and I'm not getting any error messages upon startup). 

Car reflections seem to be working, but the road reflections don't appear to be working right, and the rear-view mirror does not render the world, I can only see some lights and the opponents' cars in what appears to be a void.

Regardless of what happens in the future, thanks a lot for your work, I'm loving the Carbon version of the mod, so good to finally get rid of the "mirror cars" and lifeless world. Wish the pause menu blur would be added as optional settings in a future update though.

**Comment by AeroWidescreen** [comment]
Maye. If you could provide me with the executable then I could take a look.

**Comment by AeroWidescreen** [comment]
Maybe. If you could provide me with the executable then I could take a look.

**Comment by AeroWidescreen** [comment]
Maybe. If you could provide me with the executable then I could take a look. It has to be v1.4 though.

**Comment by sinisterseed** [comment]
Very well, here's the executable I was using. It's the v1.4 made by SPiRiTY: https://drive.google.com/file/d/1nmQjqCXbiTieglMQ7Da86TTN9WQOUric/view?usp=sharing

**Comment by AeroWidescreen** [comment]
Thanks. I don't think the executable is the problem after testing it. The mirror is rendering the world, road reflections are fully detailed, and everything looks normal. I also checked some of the memory addresses and they all match up. 

If there is a problem then it's likely going to be caused by different game files. In the meanwhile, try using `ImproveReflectionLOD = 0` and tell me if that fixes anything. I do several data checks for that feature, so it's possible that's what's causing all of your problems.

**Comment by AeroWidescreen** [comment]
Thanks. There's some kind of incompatibility with RestoreSkybox. I'll see what I can do about it. In the meanwhile, you can disable it and everything should be fine.

**Comment by AeroWidescreen** [comment]
Actually, could you tell me if this works for you:

[NFSUHDReflectionsEU-TEST.zip](https://mega.nz/#!pWJCjIiQ!vww8Fc-usgUlgWTD3Q8EdIUPtq01b8-UeSSVqRAogRo)

**Comment by sinisterseed** [comment]
Hey, sorry for getting back to this so late, but unfortunately I don't have the answer I would've liked to give... but I'm leaving it here to avoid the impression that I opened this request and then suddenly vanished.

I have since managed to find an US version of the game to be able to use the mod... I'll have to see if I have the time to reinstall the European version again for testing purposes...

**Comment by AeroWidescreen** [comment]
No problem. I'm 99% sure I got it working with the exe you uploaded, but since I don't actually have the EU version I was hoping you could confirm this. Some of the addresses I was using were slightly different. The problems you were having were fixed after I corrected them.

**Comment by AeroWidescreen** [comment]
https://github.com/AeroWidescreen/NFSUHDReflections/commit/74015c6b7acfc097577cd9e53630d82e936b9be1
